### PR TITLE
Fix virtualenv/Windows issue ImportError: No module named django.core

### LINKED ISSUE #168: Possible fix for ImportError: No module named django.core
I tried your installer in a virtualenv in Windows 7.  I kept getting the same error as this guy: https://github.com/nephila/djangocms-installer/issues/165

I ended up having to change one line in djangocms_installer\django\__init__.py

In the create_project function, I changed the syntax from:

subprocess.check_call(' '.join(['django-admin.py', 'startproject'] + args), shell=True)

to:

subprocess.check_call(' '.join(['python virtualenv_path\Scripts\django-admin.py', 'startproject'] + args), shell=True)

After that, the installation process went pretty smoothly.  Not sure how others have tackled this problem, but I was thinking that this might be helpful to others Windows users trying to install django cms.

Update: I'm using Python 2.7.8

### PR DESCRIPTION
**Pull request by clk824**
Fix #168

### CODE REVIEW

**Comment by yakky** [comment]
While I think this is a viable solution, this PR assumes that ``django-admin.py`` is in the same directory as the python executable, which is a safe assumption in almost every case.
If this helps improving support on Windows, I'm ok with it, but I think a note about this assumption should be added to the readme. @clk824 could you take care of this?

**Comment by clk824** [comment]
ok

**Comment by yakky** [comment]
@clk824 thanks!

**Comment by yakky** [comment]
@clk824 I'll the note myself, thanks for the contribution!

**Pull request merged**
