### PR TITLE
Force os.environ keys to correct string type

### LINKED ISSUE #217: environment can only contain strings ("moved" from django-cms)
Please see closed issue: https://github.com/divio/django-cms/issues/4755. It is closed on django-cms, but is current open here.

### PR DESCRIPTION
**Pull request by yakky**
Fix #217 
Fix divio/django-cms#4755
Fix divio/django-cms#4861

Hopefully

### CODE REVIEW

**Comment by yakky** [comment]
@chengaomin @TheDeadOne I can wait a few days before merging this awaiting for your comments. Thanks for any contribution to the resolution of this issue

**Comment by chengaomin** [comment]
@yakky Thanks,I'll try next time

**Comment by baster33** [comment]
@yakky I am afraid this did not fixed it. I have the same issue:

Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\User\.virtualenvs\skinsground\Scripts\djangocms.exe\__main__.py", line 9, in <module>
  File "C:\Users\User\.virtualenvs\skinsground\lib\site-packages\djangocms_installer\main.py", line 41, in execute
    django.setup_database(config_data)
  File "C:\Users\User\.virtualenvs\skinsground\lib\site-packages\djangocms_installer\django\__init__.py", line 411, in s
etup_database
    env=env
  File "C:\Python27\Lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python27\Lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\Lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\Lib\subprocess.py", line 958, in _execute_child
    startupinfo)
TypeError: environment can only contain strings

Whith following os.environ:

Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ
{'TMP': 'C:\\Users\\User\\AppData\\Local\\Temp', 'COMPUTERNAME': 'USER-KOMPUTER', 'VS110COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\Tools\\', 'USERDOMAIN': 'User-Komputer', 'PSMODULEPATH': 'C:\\Users\\User\\Documents\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'VS90COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\Common7\\Tools\\', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files',
 'PROCESSOR_REVISION': '3c03', 'SYSTEMROOT': 'C:\\Windows', 'PATH': 'C:\\Users\\User\\.virtualenvs\\skinsground/Scripts;%SystemRoot%\\system32\\WindowsPowerShell\\v1.0\\;c:\\mingw\\bin;C:\\Program Files\\Common Files\\Microsoft Shared\\Microsoft Online Services;C:\\Program Files (x86)\\Common Files\\Microsoft Shared\\Microsoft Online Services;C:\\ProgramData
\\Oracle\\Java\\javapath;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\OpenCL SDK
\\3.0\\bin\\x86;C:\\Program Files (x86)\\Intel\\OpenCL SDK\\3.0\\bin\\x64;C:\\Program Files\\Intel\\Intel(R) ManagementEngine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IP
T;D:\\Program Files\\Tortoise SVN\\bin;D:\\Program Files\\OpenVPN\\bin;D:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\;D:\\Program Files\\nodejs\\;D:\\Program Files (x86)\\Git\\bin;D:\\Program Files (x86)\\Git\\cmd;C:\\Users\\User\\AppData\\Roaming\\npm;D:\\Program Files\\gettext-utils\\bin;C:\\Program Files (x86)\\Skype\\Phone\\', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'WINDOWS_TRACING_FLAGS': '3', 'VIRTUAL_ENV': 'C:\\Users\\User\\.virtualenvs\\skinsground', 'TEMP': 'C:\\Users\\User\\AppData\\Local\\Temp', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'LOCALAPPDATA': 'C:\\Users\\User\\AppData\\Local', 'HOMEPATH': '\\Users\\User', 'ERLANG_HOME': 'C:\\Program Files\\erl6.4', 'USERNAME': 'User', 'WORKON_HOME': 'C:\\Users\\User/.virtualenvs', 'LOGONSERVER': '\\\\USER-KOMPUTER', 'SESSIONNAME': 'Console', 'PROGRAMDATA': 'C:\\ProgramData', 'ESET_OPTIONS': ' ', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'FP_NO_HOST_CHECK': 'NO', 'WINDIR': 'C:\\Windows', 'WINDOWS_TRACING_LOGFILE': 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.log', 'HOMEDRIVE': 'C:', 'SYSTEMDRIVE': 'C:', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'NUMBER_OF_PROCESSORS': '4', 'APPDATA': 'C:\\Users\\User\\AppData\\Roaming', 'PROCESSOR_LEVEL': '6', 'PROGRAMW6432': 'C:\\Program Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'USERPROFILE': 'C:\\Users\\User'}

I changed file djangocms_installer/django/__init__.py in my virtualenv, but unfortunately error is still showing up.

**Comment by yakky** [comment]
@baster33 thanks for checking, back to the drawing board :(

**Comment by baster33** [comment]
@yakky No problem i was looking for solution over internet and tried that one ;)

I found something that might be usefull for You:
https://github.com/nvie/pip-tools/issues/209

"One suggestion is to remove the unicode_literals __future__ import" i tried this one and succesfully started project using djangocms command.

**Comment by yakky** [comment]
@baster33 actually I implemented the fix wrong (it only fixed the environ key part, not the value)
I would like to keep ``unicode_literals`` in as it's a much cleaner and sensible approach (e.g.: IMHO if it does not work with ``unicode_literals`` you're doing it wrong)

**Comment by baster33** [comment]
@yakky I understand. You current fix works as well for my case. Thank You very much :)

**Comment by yakky** [comment]
@baster33 awesome, merging and releasing soon

**Pull request merged**
