### PR TITLE
UTC as default timezone

### PR DESCRIPTION
**Pull request by deronnax**

### CODE REVIEW

**Comment by yakky** [comment]
Not sure if UTC it's the right default (actually there is no right default, current one is just happen to be the Django default)

**Comment by deronnax** [comment]
I also have a patch put the current timezone of the computer running djangocms-installer, but I think the right default is UTC. In any case, America/Chicago is not the right default. So it's "current timezone" vs "UTC". But Django made UTC as default for a reason, UTC datetimes is *the* good practice
https://docs.djangoproject.com/en/1.7/topics/i18n/timezones/

**Comment by yakky** [comment]
Getting the current timezone would be awesome!
`America/Chicago` used to be the historic default: my  fault I didn't acked the new default

**Comment by deronnax** [comment]
I did some research and local timezone in Olson format (the one that look like 'Continent/City', which is useful to django, python stdlib can only give us hardly usable thing like ('CET', 'CEST') ) can only be determined with some heavy lifting which change depending the linux distribution and the init deamon. A Python project manages to reliably and in portable manner determine that : https://github.com/regebro/tzlocal. Are you OK to add a dependency to it ? I think it would be a huge user experience improvement for few-to-middle experienced users.
If you're OK, I'll do the pull request.

**Comment by deronnax** [comment]
@yakky ?

**Comment by yakky** [comment]
@deronnax Sorry, I haven't received the notification.
I think it worth the added dependency, so go with it

**Comment by deronnax** [comment]
Go for it ;)

**Pull request closed without merging**
