### PR TITLE
Fix create_user.py command execution

### PR DESCRIPTION
**Pull request by yakky**
This was missing from 0.9.2 by mistake

### CODE REVIEW

**Comment by yakky** [comment]
@czpython Hopefully this should fix the issue, could you test it

**Comment by czpython** [comment]
@yakky Didn't work. Did you push a new change just now?

**Comment by yakky** [comment]
@czpython wow, super quick. Apparently merging the diff failed. I'm doing a local test, will ping you when I'm confident that everything is ready

**Comment by yakky** [comment]
@czpython Ok, it's good to go now

**Comment by czpython** [comment]
@yakky Works for me 👍

**Pull request merged**
