### PR TITLE
Fix django18 TEMPLATES

### PR DESCRIPTION
**Pull request by yakky**

### CODE REVIEW

**Comment by mrsarm** [comment]
@yakky , I tested this branch, and solved the CMS toolbar issue, but the installer still generating the ``settings.py`` file with ``django.middleware.doc.XViewMiddleware`` middleware instead of ``django.contrib.admindocs.middleware.XViewMiddleware`` for *Django 1.8*, so the web is inaccessible until you don't change that manually.

**Comment by yakky** [comment]
@mrsarm I removed ``XViewMiddleware`` completely as it's pretty much useless anyway

**Comment by mrsarm** [comment]
You are right! I don't realized before that it's the best solution according with this: https://code.djangoproject.com/ticket/7317

Thanks @yakky

**Comment by yakky** [comment]
Thanks for your tests. A fixed version should be released shortly

**Pull request merged**
